### ISSUE TITLE
SF3 support

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qsynth#14]
Now that fluidsynth is supporting the SF3 soundfont format, that would be great to support sf3 in Qsynth.
See: https://github.com/FluidSynth/fluidsynth/pull/183
For information, Musescore and Polyphone already support it, and LMMS is getting to it https://github.com/LMMS/lmms/issues/3286 .

Cheers!

**Comment by rncbc** [comment]
is this just about adding the SF3 filter (*.sf3) to the soundfont file requester dialog?

if yes then done (https://github.com/rncbc/qsynth/commit/9397c55)
thanks

**Comment by trebmuh** [comment]
Just rebuild a Qsynth with this patch and tested it with a fluidsynth 1.1.8 and it does work as expected. Thanks @rncbc !
Closing here now.
