### ISSUE TITLE
OutputMeters=true turns off reverb and chorus when using fluidsynth2

### ISSUE THREAD

**Issue by mickski56** [rncbc/qsynth#17]
As title, log window shows fluidset_reverb values changing but no reverb or chorus is heard.
set OutputMeters=false and all works as it should.

**Comment by rncbc** [comment]
Confirmed. However it's more an issue of libfluidsynth2 (>= 2.0.0) than of qsynth's alone.

**Comment by rncbc** [comment]
hopefully fixed with a hack on https://github.com/rncbc/qsynth/commit/212e869
cheers

**Comment by mickski56** [comment]
Working again here.
Thanks
