### ISSUE TITLE
Cmake build system checks for Qt5X11Extras

### ISSUE THREAD

**Issue by Jacalz** [rncbc/qsynth#23]
Currently, the program looks like it doesn’t need Qt5X11Extras when building using configure. But when running Cmake it checks for that program but it’s never used from any Abi stand point. Please remove that check from that build system :)

**Comment by rncbc** [comment]
it has been already removed on recent git head

byee

**Comment by Jacalz** [comment]
Sorry if I had understood things incorrectly, but shouldn’t the QtX11Extras check on the top of the file also be removed?

**Comment by rncbc** [comment]
which file and what check?

**Comment by Jacalz** [comment]
Sorry for being unclear about the file and what part of it:
https://github.com/rncbc/qsynth/blob/35ac6f0ad0fcc7cc3c1125216fb687746691e06f/CMakeLists.txt#L46
It was early in the morning, just before I got my tea :)

**Comment by rncbc** [comment]
got that, done in c273b9f

thanks for the heads-up

**Comment by Jacalz** [comment]
You are welcome 👍
