### ISSUE TITLE
configure: error: *** FLUIDSYNTH library not found.

### ISSUE THREAD

**Issue by libasoles** [rncbc/qsynth#24]
Hi guys. When I run run `./configure` or `make` I get this error:
configure: error: *** FLUIDSYNTH library not found.

I can assure you I have fluidsynth installed. Also, I have an old version (0.4.3) of qsynth installed from the repos (in raspbian). And I play piano from time to time. So, fluidsynth is there.

 I have little experience building from source. But I guess there's a parameter to tell where is fluidsynth located right? Any clue on how to solve this?

**Comment by trebmuh** [comment]
`libfluidsynth-dev` installed?

**Comment by libasoles** [comment]
Oh, good point. No it wasn't installed. So `sudo apt install libfluidsynth-dev` did the trick.

Thanks a lot.

**Comment by trebmuh** [comment]
welcome
