### ISSUE TITLE
Add support for building with ninja after cmake

### ISSUE THREAD

**Issue by Jacalz** [rncbc/qsynth#26]
Currently there is an error if building qsynth using cmake and then trying to use ninja to build it instead of make/autotools. It complains about not finding the right directory. Ninja is far superior in every way than make and especially when it comes to the speed of the compile.

See [this text](https://sourceforge.net/p/itpp/blog/2012/09/using-cmake-with-ninja-build-system/) for more info on building with ninja. I recommend you to give it a go your self and correct what ever is causing the error.

**Comment by rncbc** [comment]
please propose a PR instead.

ps. me (the upstream author) is not keen to other build toolchains but autotools atm.

**Comment by Jacalz** [comment]
The problem is that I don’t have any idea about what’s wrong, I just know that it doesn’t work like the other packages I’m building with make and ninja.

I am currently the maintainer for the qsynth, qjackctl and qtractor packages in Solus (Linux distro) but I also maintain other packages. There’s some backstory as to why I do this :)

I really recommend you to at the very least look a bit more at cmake as it really is a great build system and superior to autotools in most areas. It’s faster, simpler and just in general much more modern...

**Comment by Jacalz** [comment]
This definitely seems to have been fixed in the recent cmake build system refinements that landed in master recently. Thanks for making a lot of great Linux audio applications, it's greatly appreciated :+1:
