### ISSUE TITLE
soundfont drag & drop ?

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qsynth#3]
reading at the changelog file (paragraph "version 0.1.0"), a soundfont drag & drop on the GUI looks to be possible. That said, I can't find a way to make it working. Would you mind to tell me where a SF2 should be dropped?

**Comment by rncbc** [comment]
On 09/15/2016 04:23 PM, Olivier Humbert wrote:

> reading at the changelog file (paragraph "version 0.1.0"), a soundfont
> drag & drop on the GUI looks to be possible. That said, I can't find a
> way to make it working. Would you mind to tell me where a SF2 should be
> dropped?

it's about plain mid/smf files drag-and-drop. not sf2. sorry

## cheers

rncbc aka. Rui Nuno Capela

**Comment by trebmuh** [comment]
That makes sense. Thanks for your reply.
