### ISSUE TITLE
Incorrect scale value for reverb width

### ISSUE THREAD

**Issue by mrbumpy409** [rncbc/qsynth#32]
In **src/qsynthMainForm.cpp**, line 80, QSYNTH_REVERB_WIDTH_SCALE should be set to **100.0f**, not **1.0f**.

According to the documentation, FluidSynth uses values 0-1 for reverb width (0-100%), while Qsynth's reverb width knob goes from 0 to 100. To get 100% reverb width currently, Qsynth's width knob must be set to 1. Trying to set, say 75% reverb width is impossible as the control in Qsynth cannot accept decimal values. Values above 1 (100%) are apparently accepted by FluidSynth, but whatever those values are doing makes the reverb sound horrible.

With QSYNTH_REVERB_WIDTH_SCALE set to 100.0f, Qsynth's reverb width knob now properly represents the full range of reverb width from 0% through 100%.

**Comment by rncbc** [comment]
fixed in https://github.com/rncbc/qsynth/commit/fe47ca1

thanks

**Comment by mrbumpy409** [comment]
Just realized this issue had never been closed.
