### ISSUE TITLE
DLS sound fonts can't be added

### ISSUE THREAD

**Issue by pedrolcl** [rncbc/qsynth#56]
The Open File dialog has no option to display and load DLS sound fonts. There should be a file dialog filter enabling to select  DLS files, like the existing filters for SF2 and SF3 file formats.

The problem is that not always the libfluidsynth library has support for DLS soundfonts. This format is enabled in FluidSynth only when it is linked to the "libinstpatch" library. In a similar way, the SF3 format is enabled when it is linked to the "libsndfile" library. At runtime, if a file type is not supported it will produce an error when the synthesizer is created. It would be better to detect and prevent this at build time. FluidSynth should provide a way to expose these capabilities.

**Comment by rncbc** [comment]
i guess just adding the "*.dls *.DLS" to file dialog filter and/or adding a "All files (*.*)" option would be enough, no matter if supported by libfluidsynth  or else.

**Comment by pedrolcl** [comment]
OK. That's what Tom suggested. I will send a PR.

**Comment by pedrolcl** [comment]
Please merge #58 and close this issue. Thanks!
