### ISSUE TITLE
Change the UI language translation

### ISSUE THREAD

**Issue by pedrolcl** [rncbc/qsynth#57]
The program language translation at runtime is automatically loaded and can't be changed easily (you need to use some exotic environment variables). 

Proposed enhancement: adding a setting and another display "Option..." to the corresponding dialog, so the user can choose comfortably his preferred language translation. Qt doesn't support changing translators at runtime, but this can be an option activated only after restarting the program.

**Comment by rncbc** [comment]
seems like more a windows issue? on linux it suffices to set the LANG or LC_ALL environment variables, which are pretty standard and not so exotic I guess.

**Comment by pedrolcl** [comment]
The environment variable with highest priority (for QLocale) in Linux is LANGUAGE. Some Linux distributions set this environment variable instead of/additionally to LANG and several LC_XXXX variables. So, the safest procedure is to change this one.

In Windows it doesn't work. The only way I know to change the translation of Qsynth is to change the Windows global language setting. I've not tried in mac.

**Comment by pedrolcl** [comment]
By the way, testing this in Linux:

1. You can change the interface language of the flatpak, if you run it with this command:
~~~
$ flatpak run --env=LANGUAGE=XX org.rncbc,qsynth
~~~
This worked flawlessly in my tests. I must add: very luckily! (see below) 

2. Your AppImage does not change the UI language at all. Internationalization does not work. The user interface is always in English, no matter which environment variables you export.


I've extracted the AppImage contents to a directory for inspection...
~~~
$ ./qsynth-0.9.5-49.2.x86_64.AppImage --appimage-extract
~~~
The above command creates a directory "squashfs-root". The first observation is that you included all the sources and intermediate build products in the AppImage. :roll_eyes: 

The Qt translations are located at `usr/translations/` and qsynth translations are located at `usr/share/qsynth/translations/`(duplicated at `src/`) . But obviously the program is unable to find them. The problem is "qsynth.cpp" where `CONFIG_PREFIX` is always `/usr/local` because you never `#include "config.h"` where it is defined at configuration time. From this point, every path is wrong. I would suggest to use the prefix from QCoreApplication::applicationDirPath() which is the default, as you can see in `usr/bin/qt.conf`.

**Comment by rncbc** [comment]
config.h is included through qsynth.h which includes qsynthAbout.h in turn...

but you're right re. the AppImage though, it doesn't get the correct  translations (*.qm) path ever... maybe your suggestion to take `QCoreApplication::applicationDirPath()` into consideration might be a good solution.

thanks again && cheers

**Comment by rncbc** [comment]
> but you're right re. the AppImage though, it doesn't get the correct translations (*.qm) path ever... maybe your suggestion to take `QCoreApplication::applicationDirPath()` into consideration might be a good solution.
> 

might be fixed in 81dad27 (develop branch)

**Comment by pedrolcl** [comment]
> might be fixed in [81dad27](https://github.com/rncbc/qsynth/commit/81dad27730f4052b0613e56fef090458d5effe4a) (develop branch)

I've not built an AppImage to test, but I think that it should work (for Linux). In Windows and Mac, the installed directories are quite different. For instance in Windows, this is the layout:

~~~
C:\PROGRAM FILES\QSYNTH
│   D3Dcompiler_47.dll
│   fluidsynth.exe
│   libFLAC-8.dll
│   libfluidsynth-3.dll
│   libgcc_s_seh-1.dll
│   libglib-2.0-0.dll
│   libgomp-1.dll
│   libiconv-2.dll
│   libintl-8.dll
│   libogg-0.dll
│   libopus-0.dll
│   libpcre-1.dll
│   libreadline8.dll
│   libsndfile-1.dll
│   libssp-0.dll
│   libstdc++-6.dll
│   libtermcap-0.dll
│   libvorbis-0.dll
│   libvorbisenc-2.dll
│   libwinpthread-1.dll
│   opengl32sw.dll
│   qsynth.exe
│   Qt6Core.dll
│   Qt6Gui.dll
│   Qt6Network.dll
│   Qt6Svg.dll
│   Qt6Widgets.dll
│   uninstall.exe
│   
├───iconengines
│       qsvgicon.dll
│       
├───imageformats
│       qgif.dll
│       qico.dll
│       qjpeg.dll
│       qsvg.dll
│       
├───platforms
│       qwindows.dll
│       
├───styles
│       qwindowsvistastyle.dll
│       
└───translations
        qsynth_cs.qm
        qsynth_de.qm
        qsynth_es.qm
        qsynth_fr.qm
        qsynth_ru.qm
        qsynth_sr.qm
        qt_cs.qm
        qt_de.qm
        qt_es.qm
        qt_fr.qm
        qt_ru.qm
~~~

Anyway, it should work on Windows too because the `else` won't execute. Instead, the first `load()`should work, as I've placed all the translations, from Qt and qsynth, at the same location:
https://github.com/rncbc/qsynth/blob/2dc5f27438c2bcdb02311345646a397ce3b2fc88/src/qsynth.cpp#L132-L134

This is what I do on my own projects:
https://github.com/pedrolcl/VMPK/blob/2e41a3c1831857936a334ed34a59cd883329c33e/src/vpianosettings.cpp#L76-L100

**Comment by pedrolcl** [comment]
What you didn't answer yet is if you approve my proposal:

> Proposed enhancement: adding a setting and another display "Option..." to the corresponding dialog, so the user can choose comfortably his preferred language translation. Qt doesn't support changing translators at runtime, but this can be an option activated only after restarting the program.

**Comment by rncbc** [comment]
> > might be fixed in [81dad27](https://github.com/rncbc/qsynth/commit/81dad27730f4052b0613e56fef090458d5effe4a) (develop branch)
> 
> I've not built an AppImage to test, but I think that it should work (for Linux). In Windows and Mac, the installed directories are quite different. For instance in Windows, this is the layout:
> ...

according to that layout, then something similar to qjackctl, might do: 6ca7bf3

**Comment by rncbc** [comment]
> What you didn't answer yet is if you approve my proposal:
> 
> > Proposed enhancement: adding a setting and another display "Option..." to the corresponding dialog, so the user can choose comfortably his preferred language translation. Qt doesn't support changing translators at runtime, but this can be an option activated only after restarting the program.

approved on the condition that it won't show/apply to regular GNU/Linux builds and/or installations ;)

**Comment by pedrolcl** [comment]
> approved on the condition that it won't show/apply to regular GNU/Linux builds and/or installations ;)

I don't understand why you want to take away a feature to some users and not to others. 

Here is a random sample of music applications, running in Linux, that allow the users to choose the translation...

![Screenshot_20220115_194401](https://user-images.githubusercontent.com/15184708/149634434-3b72d72c-eb12-4b34-99cc-63f25052c7e9.png)
![Screenshot_20220115_194509](https://user-images.githubusercontent.com/15184708/149634435-d7d81f26-5326-4534-a8b3-2b1e24fd3964.png)
![Screenshot_20220115_195108](https://user-images.githubusercontent.com/15184708/149634437-8f6bec0f-efe4-4044-93be-ab9152c59f0b.png)
![Screenshot_20220115_195924](https://user-images.githubusercontent.com/15184708/149634511-05745e8c-a5a9-41be-bb8b-f847dbcf72c7.png)

**Comment by pedrolcl** [comment]
There are more... 
![Screenshot_20220115_202152](https://user-images.githubusercontent.com/15184708/149635162-947033df-0941-4365-8bcd-940f7fe95587.png)

all KDE aplications...
![Screenshot_20220115_201736](https://user-images.githubusercontent.com/15184708/149635171-21c387fc-c603-43d8-b0e7-dc1a872e7403.png)

**Comment by rncbc** [comment]
go ahead if you insist
