### ISSUE TITLE
No terminal output in Windows

### ISSUE THREAD

**Issue by pedrolcl** [rncbc/qsynth#63]
Windows GUI programs don't produce output on the terminal. This means that the command line options `--help` and `--version` are completely and silently ignored in that operating system. Error messages related to the command line options aren't displayed, either.

Other Qt programs, using the class [QCommandLineParser](https://doc.qt.io/qt-6/qcommandlineparser.html), show a message box dialog in those cases:

![vmpk_help](https://user-images.githubusercontent.com/15184708/151212925-1da0af3c-68d3-41ae-9a35-2e7aa749c004.png)

The suggestion is to implement something similar in Qsynth, without migrating to QCommandLineParser.

**Comment by rncbc** [comment]
you may well migrate it all to [QCommalineParser](https://doc.qt.io/qt-6/qcommandlineparser.html), if you wish, thanks

**Comment by pedrolcl** [comment]
I was working on the migration to qcommandline parser, and ended creating a Qt bug:
https://bugreports.qt.io/browse/QTBUG-100321
That was quickly closed, as conforming to getopt(3)
https://man7.org/linux/man-pages/man3/getopt.3.html#NOTES
