### ISSUE TITLE
init ladspa's on channel(s) as part of patch

### ISSUE THREAD

**Issue by coderofsalvation** [rncbc/qsynth#77]
One of the things about qsynth is that it's a run-and-jam-frontend for fluidsynth, the gold standard of soundfont playback.
Something what I would like is setting up a ladspa on the master, or a different ladspa on the reverb/chorus channel.
Heck, I even would not mind setting a highpass-filter ladspa on that lead-synth as well.
Any idea on doing the following with qsynth:

https://github.com/FluidSynth/fluidsynth/blob/master/doc/ladspa.md

This is a bit of gray area I guess, because on one hand qsynth is a fluidsynth frontend, but on the other hand it might fall outside of the 'patch'-scope.
Any thoughts on this?

**Comment by rncbc** [comment]
LADSPA plugin insertion and mangemente is not in the plans, sorry.

but thanks.
